name: Build and push test container to Docker Hub

on:
  push:
    paths:
      - pyproject.toml
      - poetry.lock
      - Dockerfile
      - .github/workflows/build_container.yaml
    branches:
      - main

  pull_request:
    paths:
      - pyproject.toml
      - poetry.lock
      - Dockerfile
      - .github/workflows/build_container.yaml
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: gonzz/music-matcher
          flavor: latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
